version: '3.8'

services:
  neoplast_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neoplast-backend
    ports:
      - "${APP_PORT:-8004}:${APP_PORT:-8004}"
    env_file:
      - .env
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - neoplast_network

volumes:
  backend_data:

networks:
  neoplast_network:
    name: neoplast_network
    driver: bridge